### ISSUE TITLE
[MT-007] UX for Deleting folders needed. [ENC-617] Editors (or non-admins?) folder deletions don't persist

### ISSUE THREAD

**Issue by philipwisner** [mathematicalthinking/encompass#80]
I made a workspace and made Michael Pershan an editor, and when he deleted folders   he'd added, they didn't go away (i.e. when he logged back in to the workspace later they were back). However, it seems that I was successfully able to   delete the same folders. I am an admin and the maker of the workspace.

**Comment by tayloredwebsites** [comment]
I do not know how to delete a folder, and it is not obvious in the UI
