### ISSUE TITLE
[MT-001] Images need to be stored in Encompass (both submission and problems). see also [ENC-620] Images in EnCoMPASS link to the wrong larger version

### ISSUE THREAD

**Issue by philipwisner** [mathematicalthinking/encompass#83]
Images in EnCoMPASS link to larger versions of themselves, but unfortunately, they all seem to link to the same image (the first image in the workspace). We noticed it here where every submission has an [image](http://mathforum.org/encompass/assess/#/workspaces/558228e2e1e7d9a4060000aa/submissions/558228de729e9ef59ba84baa)             

They all link to this [one](http://mathforum.org/pows/uploaded-images/VISUAL%20PTTERNS%20%20BOTHSIDE-page-037_20150617170037183-0400.jpg)

**Comment by tayloredwebsites** [comment]
Images for submissions need to be pulled from the new Answers and Problems schemas.
