### ISSUE TITLE
[MT-006] Show / Hide selections not working when switching student or revision. [ENC-495] Show selections isn't working (probably for public non-editor workspaces)

### ISSUE THREAD

**Issue by philipwisner** [mathematicalthinking/encompass#93]
[link](http://mathforum.org/encompass/assess/#/workspaces/53b585ec32f28632400012e4/submissions/53b585ec32f2863240001267)

**Comment by tayloredwebsites** [comment]
Highlighting of selections is not properly reset when changing a student or revision.  To reproduce, click to 'Show Selections'. Highlight some selections if needed.  Then change student, and the highlights will still be displayed until 'Hide Selections" is clicked.  Selections are correctly hidden after clicking 'Show Selection'.

**Comment by philipwisner** [comment]
Dan fixed this
